[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Aadesh-Baral", email = "elkloppiko@gmail.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}


[tool.pdm]
