[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Aadesh-Baral", email = "elkloppiko@gmail.com"},
]
dependencies = [
    "flask>=2.2.2",
    "sqlalchemy>=1.4.45",
    "flask-sqlalchemy>=2.5.1",
    "Flask-Cors>=3.0.10",
    "Flask-Migrate>=4.0.0",
    "python-dotenv>=0.21.0",
    "psycopg2>=2.9.5",
]
requires-python = ">=3.8"
license = {text = "MIT"}


[tool.pdm]
